name: Daily Scholarship Email

on:
  schedule:
    - cron: '10 20 * * *' # runs every day at 8AM UTC
  workflow_dispatch: # allows you to trigger manually if needed

jobs:
  send-scholarship-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.3'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run script
        env:
          GMAIL_SENDER_EMAIL: ${{ secrets.GMAIL_SENDER_EMAIL }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
        run: python "Scholarship Scraper/main.py"
